### ISSUE TITLE
DAY1打卡

### ISSUE THREAD

**Issue by degndaixingqiu** [leetcode-pp/91alg-8-daily-check#10]
##代码

```C++
#代码

```class Solution
{
public:
    vector<int> addToArrayForm(vector<int> &a, int k)
    {
        vector<int> ans;
        for (int i = a.size() - 1; i >= 0; i--)
        {
            int tmp = a[i] + k % 10;
            k /= 10;
            if (tmp >= 10)
            {
                k++;
                tmp -= 10;
            }
            ans.push_back(tmp);
        }
        for (; k > 0; k /= 10)
            ans.push_back(k%10);
        reverse(ans.begin(), ans.end());
        return ans;
    }
};

## 复杂度

> + 时间复杂度: O(n)
> + 空间复杂度:O(n)

**Comment by Hacker90** [comment]
class Solution {
public:
    vector<int> addToArrayForm(vector<int>& num, int k) {
        vector<int>result;
        int x = 0;
        int y = 0;
        int carry  = 0;
        int i = num.size()-1;
        int tsum = 0;
        while ( i >= 0 || k > 0) {
            x = i < 0? 0:num[i];
            y = k % 10;
            tsum = x + y + carry;
            result.push_back(tsum %10);
            carry = tsum /10;
            k = k/10;
            i--;
        }
        if (carry > 0)result.push_back(carry);
        reverse(result.begin(),result.end());
        return result;

    }
};
